language: php

matrix:
  include:
    - php: 7.1
      env:
       - COMPOSER_ARG=--prefer-lowest
    - php: 7.3
    - php: 7.4
    - php: nightly
      env:
       - COMPOSER_ARG=--ignore-platform-reqs

before_script:
  - composer validate
  - composer update $COMPOSER_ARG --prefer-dist

script:
  - vendor/bin/phpunit ./tests
